default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: trinity19
  port: 5432

development:
  <<: *default
  database: four-leaf-clovers_development
  username: postgres
  password: trinity19
  host: localhost
  port: 5432

test:
  <<: *default
  database: four-leaf-clovers_test

production:
  <<: *default
  database: four-leaf-clovers_production
  username: four-leaf-clovers
  password: <%= ENV['FOUR-LEAF-CLOVERS_DATABASE_PASSWORD'] %>
